databases:
  - name: your_db_name
    databaseName: your_db_name
    user: your_db_user
    plan: free

services:
  - type: web
    name: your_app_name
    runtime: php
    buildCommand: "./render-build.sh"
    startCommand: "php artisan serve --host=0.0.0.0 --port=8080"
    env: php
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        fromSecret: app_key
      # Add other environment variables here